var { aptoide, danbooru, fbdl, GDriveDl, GoogleImage, igdl, igstalk, mediafire, mediafireV2, openAi, ChatGpt, ChatGptV2, rule34, tiktokdl, tiktokdlV2, tiktokuser, tiktokvid, tiktokStalk, tiktokSearch, pinterest, pinterestdl, ppcouple, spotifySearch, spotify, spotifydl, soundSearch, xnxxdl, xvideosdl, ytsearch, ytmp3, ytmp4 } = require("./starlights")

module.exports = {
    aptoide: aptoide,
    danbooru: danbooru,
    fbdl: fbdl,
    GDriveDl: GDriveDl,
    GoogleImage: GoogleImage,
    igdl: igdl,
    igstalk: igstalk,
    mediafire: mediafire,
    mediafireV2: mediafireV2,
    openAi: openAi,
    ChatGpt: ChatGpt,
    ChatGptV2: ChatGptV2,
    rule34: rule34,
    spotifySearch: spotifySearch,
    spotify: spotify,
    spotifydl: spotifydl,
    soundSearch: soundSearch,
    tiktokdl: tiktokdl,
    tiktokdlV2: tiktokdlV2,
    tiktokuser: tiktokuser,
    tiktokStalk: tiktokStalk,
    tiktokvid: tiktokvid,
    tiktokSearch: tiktokSearch,
    pinterest: pinterest,
    pinterestdl: pinterestdl,
    ppcouple: ppcouple,
    xnxxdl: xnxxdl,
    xvideosdl: xvideosdl,
    ytsearch: ytsearch,
    ytmp3: ytmp3,
    ytmp4: ytmp4
}